pool:
  name: Azure Pipelines
  demands: npm
  
steps:
- task: CmdLine@2
  inputs:
    script: 'npm i && npx playwright install'
  displayName: 'Install Playwright'
 

- task: Npm@1
  inputs:
      command: 'custom'
      customCommand: 'run test'
  displayName: 'Execute Test'
- task: PublishMultipleCucumberReport@1
  inputs:
    jsonDir: 'test-results'
    outputPath: 'test-results\reports'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true


